// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package users_storage

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (UserDatum, error)
	DeleteUserByUsername(ctx context.Context, username string) error
	GetAllUsersCountByCountry(ctx context.Context, dollar_1 string) (int64, error)
	GetUserByUsername(ctx context.Context, username string) (UserDatum, error)
	GetUsersByCountry(ctx context.Context, arg GetUsersByCountryParams) ([]UserDatum, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]UserDatum, error)
	UpdateUserByUsername(ctx context.Context, arg UpdateUserByUsernameParams) (UserDatum, error)
	UpsertUser(ctx context.Context, arg UpsertUserParams) (UserDatum, error)
}

var _ Querier = (*Queries)(nil)
